### PR TITLE
Adding optional secrets for tests

### PR DESCRIPTION
**Pull request by homapf**
Sometimes, tests need to have a special access in order to execute.
I'm adding 3 optional secrets fields that can be transmitted from the parent workflow using `secrets: inherit`.

### CODE REVIEW

**Review by ClementCMobile — COMMENTED** [review]
Wouldn't it be easier to have them as parameters instead of hardcoded `secrets` references?

**Comment by homapf** [comment]
This is mostly for sensitive auth data, we want it to be in secrets.

**Comment by ClementCMobile** [comment]
But this approach will force the name of the secrets right? Would there be a problem with 1. Taking the secrets as parameters, and 2. Set those parameters in the project's repo from the repo's secrets?

**Comment by homapf** [comment]
Yes it will force the name of the secrets, but that's something we can manually deal with inside the tests.

I'm not sure I understand what you are describing 🤔

**Comment by homapf** [comment]
If we transmit the secret as an input/parameter and not as a secret, github won't ensure the data is transmitted securely.

**Comment by ClementCMobile** [comment]
Oh right, let's keep our secrets then!

**Review by ClementCMobile — APPROVED** [review]

**Review by manelizzard — APPROVED** [review]

**Pull request merged**
